import { useState } from 'react'
import { BrowserOpenURL } from '../../wailsjs/runtime/runtime'
import { Copy, Download, ExternalLink, FolderOpen, Info, Trash2 } from 'lucide-react'
import { browserProxyCoreDownloadInfo, browserProxyCoreOpenLocal } from '../../modules/browser/api'
import type { BrowserProxy, ProxyCheckSettings, ProxyCoreDownloadProgress, ProxyCoreStatusResult, ProxyIPHealthResult } from '../../modules/browser/types'
import {
  CHAIN_FIRST_PROTOCOL_OPTIONS,
  CHAIN_QUICK_IMPORT_TEMPLATE,
  DIRECT_PROXY_PROTOCOL_OPTIONS,
  DIRECT_QUICK_IMPORT_TEMPLATE,
  detectProxyNodeProtocol,
  type ChainImportForm,
  type DirectImportForm,
  type ProxyDisplayInfo,
  type ProxyImportMode,
} from '../../modules/browser/pages/proxyPool/helpers'
import { toast } from '../../shared/components'
import { FishModal } from './FishFormPrimitives'

export interface FishProxyEditFormValue {
  proxyName: string
  proxyConfig: string
  preferredKernel: string
  dnsServers: string
  groupName: string
}

const modeMeta: Array<{ value: ProxyImportMode; label: string; hint: string }> = [
  { value: 'clash', label: 'Clash 订阅 / YAML', hint: '订阅地址或节点 YAML' },
  { value: 'direct', label: 'HTTP / SOCKS5', hint: '单层代理或批量文本' },
  { value: 'chain', label: '链式代理', hint: '本机出口 + 落地代理' },
]

function Field({ label, children, hint }: { label: string; children: React.ReactNode; hint?: string }) {
  return <label className="fish-field"><span>{label}</span>{children}{hint ? <small>{hint}</small> : null}</label>
}

function ChainFields({ form, proxies, onFormChange, onHopChange }: { form: ChainImportForm; proxies: BrowserProxy[]; onFormChange: (patch: Partial<ChainImportForm>) => void; onHopChange: (hop: 'first' | 'second', field: keyof ChainImportForm['first'], value: string) => void }) {
  const standardHopFields = (hop: 'first' | 'second', showProtocol = true) => <div className="fish-form-grid two">{showProtocol ? <Field label="协议"><select className="fish-select" value={form[hop].protocol} onChange={(e) => onHopChange(hop, 'protocol', e.target.value)}><option value="http">HTTP</option><option value="socks5">SOCKS5</option></select></Field> : null}<Field label="代理地址"><input className="fish-input" value={form[hop].server} onChange={(e) => onHopChange(hop, 'server', e.target.value)} /></Field><Field label="代理端口"><input className="fish-input" value={form[hop].port} onChange={(e) => onHopChange(hop, 'port', e.target.value)} /></Field><Field label="账号"><input className="fish-input" value={form[hop].username} onChange={(e) => onHopChange(hop, 'username', e.target.value)} /></Field><Field label="密码"><input className="fish-input" type="password" value={form[hop].password} onChange={(e) => onHopChange(hop, 'password', e.target.value)} /></Field></div>
  const firstProtocol = form.firstMode === 'node' ? form.firstNodeProtocol : form.first.protocol
  const nodeOptions = proxies.filter((proxy) => {
    const config = proxy.proxyConfig.trim().toLowerCase()
    return !!config && config !== 'direct://' && !config.startsWith('chain+') && detectProxyNodeProtocol(proxy.proxyConfig) === form.firstNodeProtocol
  })
  const selectedNodeId = form.firstProxyId || nodeOptions.find((proxy) => proxy.proxyConfig.trim() === form.firstProxyConfig.trim())?.proxyId || ''
  const changeFirstProtocol = (value: string) => {
    if (value === 'http' || value === 'socks5') {
      onFormChange({ firstMode: 'standard' })
      onHopChange('first', 'protocol', value)
      return
    }
    onFormChange({ firstMode: 'node', firstNodeProtocol: value as ChainImportForm['firstNodeProtocol'], ...(form.firstNodeSource === 'pool' ? { firstProxyId: '', firstProxyConfig: '' } : {}) })
  }
  const changeNodeSource = (value: ChainImportForm['firstNodeSource']) => {
    onFormChange({ firstNodeSource: value, firstProxyId: '', ...(value === 'pool' ? { firstProxyConfig: '' } : {}) })
  }
  const choosePoolNode = (proxyId: string) => {
    const proxy = nodeOptions.find((item) => item.proxyId === proxyId)
    onFormChange({ firstProxyId: proxy?.proxyId || '', firstProxyConfig: proxy?.proxyConfig || '' })
  }
  return <div className="fish-proxy-chain-stack">
    <div className="fish-form-grid two"><Field label="代理名称"><input className="fish-input" value={form.proxyName} onChange={(e) => onFormChange({ proxyName: e.target.value })} /></Field><Field label="本地监听端口"><input className="fish-input" value={form.localPort} onChange={(e) => onFormChange({ localPort: e.target.value })} placeholder="留空自动分配" /></Field></div>
    <div className="fish-proxy-hop"><div className="fish-proxy-hop-title">第一层代理</div><div className="fish-form-grid two"><Field label="协议"><select className="fish-select" value={firstProtocol} onChange={(e) => changeFirstProtocol(e.target.value)}>{CHAIN_FIRST_PROTOCOL_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></Field>{form.firstMode === 'node' ? <Field label="节点来源"><select className="fish-select" value={form.firstNodeSource} onChange={(e) => changeNodeSource(e.target.value as ChainImportForm['firstNodeSource'])}><option value="pool">从代理池选择</option><option value="manual">手动输入</option></select></Field> : null}</div>{form.firstMode === 'node' ? form.firstNodeSource === 'pool' ? <Field label="已导入节点" hint={nodeOptions.length ? `引用代理池中的 ${form.firstNodeProtocol.toUpperCase()} 节点；节点更新后链路自动跟随。` : `代理池中暂无 ${form.firstNodeProtocol.toUpperCase()} 节点，可切换为手动输入。`}><select className="fish-select" value={selectedNodeId} onChange={(e) => choosePoolNode(e.target.value)}><option value="">{nodeOptions.length ? '请选择节点' : `暂无 ${form.firstNodeProtocol.toUpperCase()} 节点`}</option>{nodeOptions.map((proxy) => <option key={proxy.proxyId} value={proxy.proxyId}>{proxy.proxyName}{proxy.groupName ? ` · ${proxy.groupName}` : ''}</option>)}</select></Field> : <Field label={`${form.firstNodeProtocol.toUpperCase()} 节点配置`} hint="直接粘贴完整节点 URI；也支持兼容的 Clash 单节点 YAML"><textarea className="fish-textarea" rows={7} value={form.firstProxyConfig} onChange={(e) => onFormChange({ firstProxyId: '', firstProxyConfig: e.target.value })} placeholder={`${form.firstNodeProtocol}://...`} /></Field> : standardHopFields('first', false)}</div>
    <div className="fish-proxy-hop"><div className="fish-proxy-hop-title">第二层落地代理</div>{standardHopFields('second')}</div>
  </div>
}
export function FishProxyImportModal(props: {
  open: boolean; groups: string[]; proxies: BrowserProxy[]; mode: ProxyImportMode; url: string; fetchProxyId: string; resolvedUrl: string; text: string; dns: string; prefix: string; group: string; chainText: string; directText: string; chainForm: ChainImportForm; directForm: DirectImportForm; fetching: boolean; canParse: boolean;
  onClose: () => void; onParse: () => void; onFetchURL: () => void; onModeChange: (mode: ProxyImportMode) => void; onUrlChange: (value: string) => void; onFetchProxyChange: (value: string) => void; onTextChange: (value: string) => void; onDnsChange: (value: string) => void; onPrefixChange: (value: string) => void; onGroupChange: (value: string) => void; onChainTextChange: (value: string) => void; onDirectTextChange: (value: string) => void; onApplyChainJSON: () => void; onApplyDirectText: () => void; onChainFormChange: (patch: Partial<ChainImportForm>) => void; onChainHopChange: (hop: 'first' | 'second', field: keyof ChainImportForm['first'], value: string) => void; onDirectFormChange: (patch: Partial<DirectImportForm>) => void; onFillChainTemplate: () => void; onCopyChainTemplate: () => void; onFillDirectTemplate: () => void; onCopyDirectTemplate: () => void;
}) {
  const fetchOptions = props.proxies.filter((proxy) => proxy.proxyConfig.trim() && !proxy.proxyConfig.trim().toLowerCase().startsWith('direct://'))
  return <FishModal open={props.open} title="导入代理" onClose={props.onClose} extraWide footer={<><button className="fish-btn" type="button" disabled={props.fetching} onClick={props.onClose}>取消</button><button className="fish-btn primary" type="button" disabled={props.fetching || !props.canParse} onClick={props.onParse}>解析并预览</button></>}>
    <div className="fish-proxy-modal-stack">
      <div className="fish-detail-tabs fish-proxy-mode-tabs">{modeMeta.map((item) => <button className={props.mode === item.value ? 'active' : ''} type="button" key={item.value} onClick={() => props.onModeChange(item.value)}>{item.label}</button>)}</div>
      {props.mode === 'clash' ? <><div className="fish-form-grid three"><Field label="订阅 URL"><input className="fish-input" value={props.url} onChange={(e) => props.onUrlChange(e.target.value)} placeholder="https://..." /></Field><Field label="拉取方式"><select className="fish-select" value={props.fetchProxyId} onChange={(e) => props.onFetchProxyChange(e.target.value)}><option value="">直连拉取</option>{fetchOptions.map((proxy) => <option key={proxy.proxyId} value={proxy.proxyId}>{proxy.proxyName}</option>)}</select></Field><div className="fish-field fish-field-action"><span>&nbsp;</span><button className="fish-btn" type="button" disabled={!props.url.trim() || props.fetching} onClick={props.onFetchURL}>{props.fetching ? '获取中' : '从 URL 获取'}</button></div></div>{props.resolvedUrl ? <div className="fish-inline-note success">已绑定订阅：{props.resolvedUrl}</div> : null}<Field label="Clash YAML"><textarea className="fish-textarea" rows={10} value={props.text} onChange={(e) => props.onTextChange(e.target.value)} placeholder="proxies: ..." /></Field><div className="fish-form-grid three"><Field label="分组"><input className="fish-input" value={props.group} onChange={(e) => props.onGroupChange(e.target.value)} list="fish-proxy-import-groups" /></Field><Field label="名称前缀"><input className="fish-input" value={props.prefix} onChange={(e) => props.onPrefixChange(e.target.value)} /></Field><Field label="批量 DNS"><textarea className="fish-textarea compact" rows={3} value={props.dns} onChange={(e) => props.onDnsChange(e.target.value)} /></Field></div></> : null}
      {props.mode === 'direct' ? <><div className="fish-form-grid three"><Field label="协议"><select className="fish-select" value={props.directForm.protocol} onChange={(e) => props.onDirectFormChange({ protocol: e.target.value as DirectImportForm['protocol'] })}>{DIRECT_PROXY_PROTOCOL_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></Field><Field label="代理名称"><input className="fish-input" value={props.directForm.proxyName} onChange={(e) => props.onDirectFormChange({ proxyName: e.target.value })} /></Field><Field label="分组"><input className="fish-input" value={props.group} onChange={(e) => props.onGroupChange(e.target.value)} list="fish-proxy-import-groups" /></Field><Field label="服务器"><input className="fish-input" value={props.directForm.server} onChange={(e) => props.onDirectFormChange({ server: e.target.value })} /></Field><Field label="端口"><input className="fish-input" value={props.directForm.port} onChange={(e) => props.onDirectFormChange({ port: e.target.value })} /></Field><Field label="账号"><input className="fish-input" value={props.directForm.username} onChange={(e) => props.onDirectFormChange({ username: e.target.value })} /></Field><Field label="密码"><input className="fish-input" type="password" value={props.directForm.password} onChange={(e) => props.onDirectFormChange({ password: e.target.value })} /></Field></div><Field label="批量文本" hint="支持 JSON / JSON 数组 / 多行代理 URL"><textarea className="fish-textarea" rows={7} value={props.directText} onChange={(e) => props.onDirectTextChange(e.target.value)} placeholder={DIRECT_QUICK_IMPORT_TEMPLATE} /></Field><div className="fish-inline-actions"><button className="fish-btn" type="button" onClick={props.onFillDirectTemplate}>填入模板</button><button className="fish-btn" type="button" onClick={props.onCopyDirectTemplate}><Copy size={16} strokeWidth={1.8} />复制模板</button><button className="fish-btn" type="button" disabled={!props.directText.trim()} onClick={props.onApplyDirectText}>应用文本</button></div></> : null}
      {props.mode === 'chain' ? <><ChainFields form={props.chainForm} proxies={props.proxies} onFormChange={props.onChainFormChange} onHopChange={props.onChainHopChange} /><Field label="JSON 辅助"><textarea className="fish-textarea" rows={7} value={props.chainText} onChange={(e) => props.onChainTextChange(e.target.value)} placeholder={CHAIN_QUICK_IMPORT_TEMPLATE} /></Field><div className="fish-inline-actions"><button className="fish-btn" type="button" onClick={props.onFillChainTemplate}>填入模板</button><button className="fish-btn" type="button" onClick={props.onCopyChainTemplate}><Copy size={16} strokeWidth={1.8} />复制模板</button><button className="fish-btn" type="button" disabled={!props.chainText.trim()} onClick={props.onApplyChainJSON}>应用 JSON</button></div><Field label="分组"><input className="fish-input" value={props.group} onChange={(e) => props.onGroupChange(e.target.value)} list="fish-proxy-import-groups" /></Field></> : null}
      <datalist id="fish-proxy-import-groups">{props.groups.map((group) => <option key={group} value={group} />)}</datalist>
    </div>
  </FishModal>
}

export function FishProxyPreviewModal({ open, list, removedCount, importing, onClose, onBack, onConfirm, onRemove }: { open: boolean; list: ProxyDisplayInfo[]; removedCount: number; importing: boolean; onClose: () => void; onBack: () => void; onConfirm: () => void; onRemove: (id: string) => void }) {
  return <FishModal open={open} title="确认导入" onClose={onClose} wide footer={<><button className="fish-btn" type="button" onClick={onBack}>返回修改</button><button className="fish-btn primary" type="button" disabled={!list.length || importing} onClick={onConfirm}>{importing ? '导入中' : `导入 ${list.length} 条`}</button></>}><div className="fish-inline-note">保留 {list.length} 条，移除 {removedCount} 条。</div><div className="fish-proxy-preview-list">{list.map((item) => <div className="fish-proxy-preview-row" key={item.proxyId}><div><strong>{item.proxyName}</strong><span>{item.type.toUpperCase()} · {item.server}:{item.port || '—'}</span></div><button className="fish-mini-icon danger" type="button" onClick={() => onRemove(item.proxyId)}><Trash2 size={16} strokeWidth={1.8} /></button></div>)}</div></FishModal>
}

export function FishProxyEditModal(props: { open: boolean; saving: boolean; groups: string[]; proxies: BrowserProxy[]; form: FishProxyEditFormValue; chainMode: boolean; chainForm: ChainImportForm; directMode: boolean; directForm: DirectImportForm; onClose: () => void; onSave: () => void; onChange: (patch: Partial<FishProxyEditFormValue>) => void; onChainFormChange: (patch: Partial<ChainImportForm>) => void; onDirectFormChange: (patch: Partial<DirectImportForm>) => void; onChainHopChange: (hop: 'first' | 'second', field: keyof ChainImportForm['first'], value: string) => void }) {
  const name = props.chainMode ? props.chainForm.proxyName : props.directMode ? props.directForm.proxyName : props.form.proxyName
  const hy2Chain = props.chainMode && props.chainForm.firstMode === 'node' && props.chainForm.firstNodeProtocol === 'hysteria2'
  const chainKernel = hy2Chain ? 'sing-box' : 'xray'
  const kernelValue = props.chainMode && !['auto', chainKernel].includes(props.form.preferredKernel || 'auto') ? 'auto' : props.form.preferredKernel || 'auto'
  return <FishModal open={props.open} title="编辑代理" onClose={props.onClose} wide footer={<><button className="fish-btn" type="button" onClick={props.onClose}>取消</button><button className="fish-btn primary" type="button" disabled={props.saving} onClick={props.onSave}>{props.saving ? '保存中' : '保存'}</button></>}><div className="fish-proxy-modal-stack"><div className="fish-form-grid two"><Field label="代理名称"><input className="fish-input" value={name} onChange={(e) => props.chainMode ? props.onChainFormChange({ proxyName: e.target.value }) : props.directMode ? props.onDirectFormChange({ proxyName: e.target.value }) : props.onChange({ proxyName: e.target.value })} /></Field><Field label="分组"><input className="fish-input" value={props.form.groupName} onChange={(e) => props.onChange({ groupName: e.target.value })} list="fish-proxy-edit-groups" /></Field><Field label="代理内核"><select className="fish-select" value={kernelValue} onChange={(e) => props.onChange({ preferredKernel: e.target.value })}><option value="auto">自动</option>{props.chainMode ? <option value={chainKernel}>{hy2Chain ? 'sing-box' : 'Xray'}</option> : <><option value="xray">Xray</option><option value="sing-box">sing-box</option><option value="mihomo">Mihomo</option></>}</select></Field></div>{props.chainMode ? <ChainFields form={props.chainForm} proxies={props.proxies} onFormChange={props.onChainFormChange} onHopChange={props.onChainHopChange} /> : props.directMode ? <div className="fish-form-grid two"><Field label="协议"><select className="fish-select" value={props.directForm.protocol} onChange={(e) => props.onDirectFormChange({ protocol: e.target.value as DirectImportForm['protocol'] })}>{DIRECT_PROXY_PROTOCOL_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></Field><Field label="服务器"><input className="fish-input" value={props.directForm.server} onChange={(e) => props.onDirectFormChange({ server: e.target.value })} /></Field><Field label="端口"><input className="fish-input" value={props.directForm.port} onChange={(e) => props.onDirectFormChange({ port: e.target.value })} /></Field><Field label="账号"><input className="fish-input" value={props.directForm.username} onChange={(e) => props.onDirectFormChange({ username: e.target.value })} /></Field><Field label="密码"><input className="fish-input" type="password" value={props.directForm.password} onChange={(e) => props.onDirectFormChange({ password: e.target.value })} /></Field></div> : <Field label="代理配置"><textarea className="fish-textarea" rows={9} value={props.form.proxyConfig} onChange={(e) => props.onChange({ proxyConfig: e.target.value })} /></Field>}<Field label="DNS 服务器"><textarea className="fish-textarea" rows={5} value={props.form.dnsServers} onChange={(e) => props.onChange({ dnsServers: e.target.value })} /></Field><datalist id="fish-proxy-edit-groups">{props.groups.map((group) => <option key={group} value={group} />)}</datalist></div></FishModal>
}

export function FishProxyHealthModal({ open, detail, onClose }: { open: boolean; detail: ProxyIPHealthResult | null; onClose: () => void }) {
  return <FishModal open={open} title="IP 健康原始结果" onClose={onClose} wide footer={<button className="fish-btn" type="button" onClick={onClose}>关闭</button>}>{detail ? <div className="fish-proxy-health-detail"><div className="fish-inline-note">{detail.proxyId} · {detail.source || 'unknown'} · {detail.updatedAt || '—'}</div>{!detail.ok ? <div className="fish-alert error"><strong>检测失败</strong><span>{detail.error || '未知错误'}</span></div> : null}<pre>{JSON.stringify(detail.rawData || {}, null, 2)}</pre></div> : null}</FishModal>
}

export function FishProxyCheckSettingsModal(props: { open: boolean; settings: ProxyCheckSettings; targetsText: string; saving: boolean; onClose: () => void; onSave: () => void; onSettingsChange: React.Dispatch<React.SetStateAction<ProxyCheckSettings>>; onTargetsTextChange: (value: string) => void }) {
  return <FishModal open={props.open} title="检测设置" onClose={props.onClose} wide footer={<><button className="fish-btn" type="button" onClick={props.onClose}>取消</button><button className="fish-btn primary" type="button" disabled={props.saving} onClick={props.onSave}>{props.saving ? '保存中' : '保存'}</button></>}><div className="fish-proxy-modal-stack"><div className="fish-form-grid three"><Field label="桥接启动等待"><input className="fish-input" type="number" value={props.settings.bridgeStartTimeoutMs} onChange={(e) => props.onSettingsChange((current) => ({ ...current, bridgeStartTimeoutMs: Number(e.target.value) || 15000 }))} /></Field><Field label="测速目标 ID"><input className="fish-input" value={props.settings.speedTargetId} onChange={(e) => props.onSettingsChange((current) => ({ ...current, speedTargetId: e.target.value }))} /></Field><Field label="IP 健康目标 ID"><input className="fish-input" value={props.settings.ipHealthTargetId} onChange={(e) => props.onSettingsChange((current) => ({ ...current, ipHealthTargetId: e.target.value }))} /></Field></div><Field label="检测目标列表（JSON）"><textarea className="fish-textarea" rows={13} value={props.targetsText} onChange={(e) => props.onTargetsTextChange(e.target.value)} /></Field></div></FishModal>
}

export function FishProxyCoreModal(props: { open: boolean; core: string; goos: string; goarch: string; downloadProxy: string; progress: ProxyCoreDownloadProgress | null; status: ProxyCoreStatusResult | null; statusLoading: boolean; onCoreChange: (value: string) => void; onGOOSChange: (value: string) => void; onGOARCHChange: (value: string) => void; onDownloadProxyChange: (value: string) => void; onClose: () => void; onStart: () => void }) {
  const [manualLoading, setManualLoading] = useState(false)
  const downloading = !!props.progress && !['done', 'error'].includes(props.progress.phase)
  const openRemote = async () => { setManualLoading(true); try { const info = await browserProxyCoreDownloadInfo(props.core, props.goos, props.goarch, props.downloadProxy); const url = info.downloadUrl || info.releaseUrl; if (!url) { toast.error(info.message || '没有可打开的远程地址'); return } BrowserOpenURL(url) } catch (error) { toast.error(error instanceof Error ? error.message : '打开远程地址失败') } finally { setManualLoading(false) } }
  const openLocal = async () => { try { const ok = await browserProxyCoreOpenLocal(props.core, props.goos, props.goarch); if (!ok) toast.error('未连接后端') } catch (error) { toast.error(error instanceof Error ? error.message : '打开本地目录失败') } }
  const close = () => { if (downloading) { toast.warning('正在下载中，请稍候'); return } props.onClose() }
  return <FishModal open={props.open} title="代理内核" onClose={close} footer={<><button className="fish-btn" type="button" disabled={downloading} onClick={close}>关闭</button><button className="fish-btn primary" type="button" disabled={downloading} onClick={props.onStart}><Download size={16} strokeWidth={1.8} />{downloading ? '下载中' : '开始下载'}</button></>}><div className="fish-proxy-modal-stack"><div className="fish-form-grid two"><Field label="代理内核"><select className="fish-select" value={props.core} disabled={downloading} onChange={(e) => props.onCoreChange(e.target.value)}><option value="xray">Xray</option><option value="mihomo">Mihomo</option><option value="sing-box">sing-box</option></select></Field><Field label="内核状态"><div className={`fish-static-field${props.status?.installed ? ' good' : ''}`}>{props.statusLoading ? '检测中…' : props.status?.message || '未知'}</div></Field><Field label="目标系统"><select className="fish-select" value={props.goos} disabled={downloading} onChange={(e) => props.onGOOSChange(e.target.value)}><option value="windows">Windows</option><option value="linux">Linux</option><option value="darwin">macOS</option></select></Field><Field label="目标架构"><select className="fish-select" value={props.goarch} disabled={downloading} onChange={(e) => props.onGOARCHChange(e.target.value)}><option value="amd64">amd64 / x64</option><option value="arm64">arm64</option><option value="386">386 / x86</option></select></Field></div><Field label="下载代理"><input className="fish-input" value={props.downloadProxy} disabled={downloading} onChange={(e) => props.onDownloadProxyChange(e.target.value)} placeholder="默认直连；如 socks5://127.0.0.1:7890" /></Field>{props.progress ? <div className="fish-progress-card"><div><span>{props.progress.message}</span><strong>{props.progress.progress}%</strong></div><div className="fish-progress-track"><span style={{ width: `${Math.max(0, Math.min(100, props.progress.progress))}%` }} /></div></div> : null}<div className="fish-inline-actions"><button className="fish-btn" type="button" disabled={downloading} onClick={() => void openLocal()}><FolderOpen size={16} strokeWidth={1.8} />本地目录</button><button className="fish-btn" type="button" disabled={downloading || manualLoading} onClick={() => void openRemote()}><ExternalLink size={16} strokeWidth={1.8} />远程地址</button></div></div></FishModal>
}

export function FishProxyGuideModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  return <FishModal open={open} title="代理池使用说明" onClose={onClose} wide footer={<button className="fish-btn primary" type="button" onClick={onClose}>知道了</button>}><div className="fish-guide-grid"><div><Info size={20} strokeWidth={1.8} /><strong>Clash 订阅 / YAML</strong><span>可直连或借助已有代理拉取订阅；解析后先预览再写入代理池。</span></div><div><Info size={20} strokeWidth={1.8} /><strong>HTTP / SOCKS5</strong><span>支持单个表单、JSON、JSON 数组和多行代理 URL。</span></div><div><Info size={20} strokeWidth={1.8} /><strong>链式代理</strong><span>第一层可直接使用 VLESS / VMess / Trojan / SS 或 HTTP/SOCKS5，第二层连接落地 HTTP/SOCKS5；由 Xray 建立两跳链路。</span></div></div></FishModal>
}
