package mcpserver

import (
	"context"
	"encoding/json"
	"strings"

	"ant-chrome/backend/internal/launchcode"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

func registerPageTools(srv *mcp.Server,p PageProvider){registerPageNavigationTools(srv,p);registerPageInteractionTools(srv,p);registerPageReadTools(srv,p);registerPageSessionTools(srv,p)}

func registerPageNavigationTools(srv *mcp.Server,p PageProvider){
	mcp.AddTool(srv,&mcp.Tool{Name:"ant_page_goto",Description:"在目标实例中导航到 URL；后续页面操作复用同一个 CDP 会话。",Annotations:mutating("页面导航")},func(_ context.Context,_ *mcp.CallToolRequest,in gotoInput)(*mcp.CallToolResult,gotoOutput,error){args:=map[string]any{"url":strings.TrimSpace(in.URL)};if w:=strings.TrimSpace(in.WaitUntil);w!=""{args["waitUntil"]=w};fail,out,payload:=runPageAction(p,in.Selector,in.TimeoutMs,"goto",args);if fail!=nil{return fail,gotoOutput{pageOutput:out},nil};r:=gotoOutput{pageOutput:out};if s,ok:=payload["status"].(float64);ok{r.Status=int(s)};return nil,r,nil})
	mcp.AddTool(srv,&mcp.Tool{Name:"ant_page_wait",Description:"等待元素、URL 或加载状态。",Annotations:readOnly("等待页面状态")},func(_ context.Context,_ *mcp.CallToolRequest,in waitInput)(*mcp.CallToolResult,pageOutput,error){args:=map[string]any{};if e:=strings.TrimSpace(in.Element);e!=""{args["selector"]=e;if s:=strings.TrimSpace(in.State);s!=""{args["state"]=s}};if u:=strings.TrimSpace(in.URL);u!=""{args["url"]=u};if l:=strings.TrimSpace(in.LoadState);l!=""{args["loadState"]=l};fail,out,_:=runPageAction(p,in.Selector,in.TimeoutMs,"waitFor",args);if fail!=nil{return fail,out,nil};return nil,out,nil})
	mcp.AddTool(srv,&mcp.Tool{Name:"ant_page_tabs",Description:"管理标签页：list/new/select/close。",Annotations:mutating("管理标签页")},func(_ context.Context,_ *mcp.CallToolRequest,in tabsInput)(*mcp.CallToolResult,tabsOutput,error){op:=strings.TrimSpace(in.Op);if op==""{op="list"};args:=map[string]any{"op":op};if in.Index!=nil{args["index"]=*in.Index};if u:=strings.TrimSpace(in.URL);u!=""{args["url"]=u};result,err:=pageCall(p,in.Selector,in.TimeoutMs,"tabs",args);if err!=nil{return toolError(err),tabsOutput{},nil};payload,stepErr:=firstStep(result);if stepErr!=nil{return toolError(stepErr),tabsOutput{ProfileID:result.ProfileID},nil};out:=tabsOutput{ProfileID:result.ProfileID,OK:true,Page:pageStateOf(payload)};if items,ok:=payload["items"].([]any);ok{out.Items=decodeTabs(items);out.Count=len(out.Items)};return nil,out,nil})
}

func registerPageInteractionTools(srv *mcp.Server,p PageProvider){
	mcp.AddTool(srv,&mcp.Tool{Name:"ant_page_click",Description:"点击元素；优先使用 snapshot 返回的 selector。",Annotations:mutating("点击元素")},func(_ context.Context,_ *mcp.CallToolRequest,in clickInput)(*mcp.CallToolResult,pageOutput,error){extra:=map[string]any{};if b:=strings.TrimSpace(in.Button);b!=""{extra["button"]=b};if in.ClickCount>0{extra["clickCount"]=in.ClickCount};if in.Force{extra["force"]=true};fail,out,_:=runPageAction(p,in.Selector,in.TimeoutMs,"click",in.args(extra));if fail!=nil{return fail,out,nil};return nil,out,nil})
	mcp.AddTool(srv,&mcp.Tool{Name:"ant_page_fill",Description:"一次填写一个或多个输入框。",Annotations:mutating("填写表单")},func(_ context.Context,_ *mcp.CallToolRequest,in fillInput)(*mcp.CallToolResult,fillOutput,error){if len(in.Fields)==0{return toolError(newInputError("fields 不能为空")),fillOutput{},nil};fields:=make([]map[string]any,0,len(in.Fields));for _,f:=range in.Fields{e:=strings.TrimSpace(f.Element);if e==""{return toolError(newInputError("每个字段都必须提供 element")),fillOutput{},nil};entry:=map[string]any{"selector":e,"value":f.Value};if frame:=strings.TrimSpace(f.FrameSelector);frame!=""{entry["frameSelector"]=frame};fields=append(fields,entry)};fail,out,payload:=runPageAction(p,in.Selector,in.TimeoutMs,"fill",map[string]any{"fields":fields});if fail!=nil{return fail,fillOutput{pageOutput:out},nil};r:=fillOutput{pageOutput:out};if filled,ok:=payload["filled"].([]any);ok{r.Filled=decodeStrings(filled)};return nil,r,nil})
	mcp.AddTool(srv,&mcp.Tool{Name:"ant_page_press",Description:"发送按键，例如 Enter、Escape、Tab、Control+A。",Annotations:mutating("键盘输入")},func(_ context.Context,_ *mcp.CallToolRequest,in pressInput)(*mcp.CallToolResult,pageOutput,error){input:=strings.TrimSpace(in.Input);if input==""{return toolError(newInputError("按键不能为空")),pageOutput{},nil};args:=map[string]any{"press":input};if e:=strings.TrimSpace(in.Element);e!=""{args["selector"]=e;if f:=strings.TrimSpace(in.FrameSelector);f!=""{args["frameSelector"]=f}};fail,out,_:=runPageAction(p,in.Selector,in.TimeoutMs,"press",args);if fail!=nil{return fail,out,nil};return nil,out,nil})
	mcp.AddTool(srv,&mcp.Tool{Name:"ant_page_select",Description:"在 select 元素中选中选项。",Annotations:mutating("选择下拉项")},func(_ context.Context,_ *mcp.CallToolRequest,in selectInput)(*mcp.CallToolResult,selectOutput,error){if len(in.Values)==0{return toolError(newInputError("values 不能为空")),selectOutput{},nil};values:=make([]any,0,len(in.Values));for _,v:=range in.Values{values=append(values,v)};fail,out,payload:=runPageAction(p,in.Selector,in.TimeoutMs,"selectOption",in.args(map[string]any{"values":values}));if fail!=nil{return fail,selectOutput{pageOutput:out},nil};r:=selectOutput{pageOutput:out};if selected,ok:=payload["selected"].([]any);ok{r.Selected=decodeStrings(selected)};return nil,r,nil})
}

func registerPageReadTools(srv *mcp.Server,p PageProvider){
	mcp.AddTool(srv,&mcp.Tool{Name:"ant_page_snapshot",Description:"返回页面 URL、标题和可交互元素及其 selector。",Annotations:readOnly("页面快照")},func(_ context.Context,_ *mcp.CallToolRequest,in snapshotInput)(*mcp.CallToolResult,snapshotOutput,error){args:=map[string]any{};if in.Limit>0{args["limit"]=in.Limit};if in.IncludeText{args["includeText"]=true};fail,out,payload:=runPageAction(p,in.Selector,in.TimeoutMs,"snapshot",args);if fail!=nil{return fail,snapshotOutput{pageOutput:out},nil};r:=snapshotOutput{pageOutput:out,Elements:[]PageElement{}};if elements,ok:=payload["elements"].([]any);ok{r.Elements=decodeElements(elements)};if text,ok:=payload["text"].(string);ok{r.Text=text};if tr,ok:=payload["truncated"].(bool);ok{r.Truncated=tr};return nil,r,nil})
	mcp.AddTool(srv,&mcp.Tool{Name:"ant_page_screenshot",Description:"截取视口、整页或指定元素并返回图片内容。",Annotations:readOnly("页面截图")},func(_ context.Context,_ *mcp.CallToolRequest,in screenshotInput)(*mcp.CallToolResult,pageOutput,error){args:=map[string]any{};if e:=strings.TrimSpace(in.Element);e!=""{args["selector"]=e};if in.FullPage{args["fullPage"]=true};if t:=strings.TrimSpace(in.Type);t!=""{args["type"]=t};if in.Quality>0{args["quality"]=in.Quality};result,err:=pageCall(p,in.Selector,in.TimeoutMs,"screenshot",args);if err!=nil{return toolError(err),pageOutput{},nil};payload,stepErr:=firstStep(result);if stepErr!=nil{return toolError(stepErr),pageOutput{ProfileID:result.ProfileID},nil};out:=pageOutput{ProfileID:result.ProfileID,OK:true,Page:pageStateOf(payload)};name,_:=payload["screenshot"].(string);shot,ok:=result.Screenshots[name];if !ok||len(shot.Data)==0{return toolError(&launchcode.ServiceError{Status:500,Message:"截图未能读取"}),out,nil};return &mcp.CallToolResult{Content:[]mcp.Content{&mcp.ImageContent{Data:shot.Data,MIMEType:shot.MIMEType}}},out,nil})
	mcp.AddTool(srv,&mcp.Tool{Name:"ant_page_extract",Description:"抽取元素文本、HTML 或属性。",Annotations:readOnly("抽取页面内容")},func(_ context.Context,_ *mcp.CallToolRequest,in extractInput)(*mcp.CallToolResult,extractOutput,error){mode:=strings.TrimSpace(in.Mode);if mode==""{mode="text"};if mode=="attribute"&&strings.TrimSpace(in.Attribute)==""{return toolError(newInputError("mode=attribute 时必须提供 attribute")),extractOutput{},nil};extra:=map[string]any{"mode":mode};if a:=strings.TrimSpace(in.Attribute);a!=""{extra["attribute"]=a};if in.All{extra["all"]=true};result,err:=pageCall(p,in.Selector,in.TimeoutMs,"extract",in.args(extra));if err!=nil{return toolError(err),extractOutput{},nil};payload,stepErr:=firstStep(result);if stepErr!=nil{return toolError(stepErr),extractOutput{ProfileID:result.ProfileID},nil};out:=extractOutput{ProfileID:result.ProfileID,OK:true,Mode:mode};if v,ok:=payload["value"].(string);ok{out.Value=v};if values,ok:=payload["values"].([]any);ok{out.Values=decodeStrings(values);out.Count=len(out.Values)};return nil,out,nil})
	mcp.AddTool(srv,&mcp.Tool{Name:"ant_page_evaluate",Description:"在页面上下文执行 JavaScript 并返回结果。",Annotations:mutating("执行页面脚本")},func(_ context.Context,_ *mcp.CallToolRequest,in evaluateInput)(*mcp.CallToolResult,evaluateOutput,error){expression:=strings.TrimSpace(in.Expression);if expression==""{return toolError(newInputError("expression 不能为空")),evaluateOutput{},nil};args:=map[string]any{"expression":expression};if in.Arg!=nil{args["arg"]=in.Arg};result,err:=pageCall(p,in.Selector,in.TimeoutMs,"evaluate",args);if err!=nil{return toolError(err),evaluateOutput{},nil};payload,stepErr:=firstStep(result);if stepErr!=nil{return toolError(stepErr),evaluateOutput{ProfileID:result.ProfileID},nil};return nil,evaluateOutput{ProfileID:result.ProfileID,OK:true,Value:payload["value"]},nil})
}

func registerPageSessionTools(srv *mcp.Server,p PageProvider){mcp.AddTool(srv,&mcp.Tool{Name:"ant_page_release",Description:"释放常驻页面会话但不关闭浏览器。",Annotations:destructive("释放页面会话")},func(_ context.Context,_ *mcp.CallToolRequest,in releaseInput)(*mcp.CallToolResult,releaseOutput,error){var selector launchcode.LaunchSelector;if in.Selector!=nil{selector=in.Selector.toLaunchSelector()};profileID,err:=p.ClosePageSession(selector);if err!=nil{return toolError(err),releaseOutput{},nil};return nil,releaseOutput{ProfileID:profileID,Released:true},nil})}

func decodeElements(items []any) []PageElement { out:=make([]PageElement,0,len(items));for _,item:=range items{data,err:=json.Marshal(item);if err!=nil{continue};var e PageElement;if json.Unmarshal(data,&e)==nil{out=append(out,e)}};return out }
func decodeTabs(items []any) []PageTab { out:=make([]PageTab,0,len(items));for _,item:=range items{data,err:=json.Marshal(item);if err!=nil{continue};var tab PageTab;if json.Unmarshal(data,&tab)==nil{out=append(out,tab)}};return out }
func decodeStrings(items []any) []string { out:=make([]string,0,len(items));for _,item:=range items{if text,ok:=item.(string);ok{out=append(out,text)}};return out }
